# Generated by Django 4.2.7 on 2023-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_hint',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='keyword',
            field=models.CharField(default='C', max_length=100),
        ),
    ]
