# Generated by Django 4.2.7 on 2023-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_challenge_challenge_hint_challenge_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_hint',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
