# Generated by Django 4.2.7 on 2023-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_challenge_challenge_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='keyword',
            field=models.CharField(default='RETO', max_length=100),
        ),
    ]
