# Generated by Django 4.2.7 on 2023-11-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_secrets_completedsecrets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedsecrets',
            old_name='Secrets',
            new_name='secrets',
        ),
    ]
